// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agynio/api/llm/v1/llm.proto

package llmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LLMService_CreateLLMProvider_FullMethodName                   = "/agynio.api.llm.v1.LLMService/CreateLLMProvider"
	LLMService_GetLLMProvider_FullMethodName                      = "/agynio.api.llm.v1.LLMService/GetLLMProvider"
	LLMService_UpdateLLMProvider_FullMethodName                   = "/agynio.api.llm.v1.LLMService/UpdateLLMProvider"
	LLMService_DeleteLLMProvider_FullMethodName                   = "/agynio.api.llm.v1.LLMService/DeleteLLMProvider"
	LLMService_ListLLMProviders_FullMethodName                    = "/agynio.api.llm.v1.LLMService/ListLLMProviders"
	LLMService_CreateModel_FullMethodName                         = "/agynio.api.llm.v1.LLMService/CreateModel"
	LLMService_GetModel_FullMethodName                            = "/agynio.api.llm.v1.LLMService/GetModel"
	LLMService_UpdateModel_FullMethodName                         = "/agynio.api.llm.v1.LLMService/UpdateModel"
	LLMService_DeleteModel_FullMethodName                         = "/agynio.api.llm.v1.LLMService/DeleteModel"
	LLMService_ListModels_FullMethodName                          = "/agynio.api.llm.v1.LLMService/ListModels"
	LLMService_CreateSubscription_FullMethodName                  = "/agynio.api.llm.v1.LLMService/CreateSubscription"
	LLMService_GetSubscription_FullMethodName                     = "/agynio.api.llm.v1.LLMService/GetSubscription"
	LLMService_UpdateSubscription_FullMethodName                  = "/agynio.api.llm.v1.LLMService/UpdateSubscription"
	LLMService_DeleteSubscription_FullMethodName                  = "/agynio.api.llm.v1.LLMService/DeleteSubscription"
	LLMService_ListSubscriptions_FullMethodName                   = "/agynio.api.llm.v1.LLMService/ListSubscriptions"
	LLMService_CreateSubscriptionAttachment_FullMethodName        = "/agynio.api.llm.v1.LLMService/CreateSubscriptionAttachment"
	LLMService_DeleteSubscriptionAttachment_FullMethodName        = "/agynio.api.llm.v1.LLMService/DeleteSubscriptionAttachment"
	LLMService_ListSubscriptionAttachments_FullMethodName         = "/agynio.api.llm.v1.LLMService/ListSubscriptionAttachments"
	LLMService_TestModel_FullMethodName                           = "/agynio.api.llm.v1.LLMService/TestModel"
	LLMService_ResolveModel_FullMethodName                        = "/agynio.api.llm.v1.LLMService/ResolveModel"
	LLMService_ResolveSubscription_FullMethodName                 = "/agynio.api.llm.v1.LLMService/ResolveSubscription"
	LLMService_CountSubscriptionsReferencingSecret_FullMethodName = "/agynio.api.llm.v1.LLMService/CountSubscriptionsReferencingSecret"
)

// LLMServiceClient is the client API for LLMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LLMService manages provider, model, and subscription resources and resolves
// them for the LLM Proxy.
type LLMServiceClient interface {
	// --- Providers ---
	CreateLLMProvider(ctx context.Context, in *CreateLLMProviderRequest, opts ...grpc.CallOption) (*CreateLLMProviderResponse, error)
	GetLLMProvider(ctx context.Context, in *GetLLMProviderRequest, opts ...grpc.CallOption) (*GetLLMProviderResponse, error)
	UpdateLLMProvider(ctx context.Context, in *UpdateLLMProviderRequest, opts ...grpc.CallOption) (*UpdateLLMProviderResponse, error)
	DeleteLLMProvider(ctx context.Context, in *DeleteLLMProviderRequest, opts ...grpc.CallOption) (*DeleteLLMProviderResponse, error)
	ListLLMProviders(ctx context.Context, in *ListLLMProvidersRequest, opts ...grpc.CallOption) (*ListLLMProvidersResponse, error)
	// --- Models ---
	CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelResponse, error)
	GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelResponse, error)
	UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*UpdateModelResponse, error)
	DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	// --- Subscriptions ---
	CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error)
	GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*GetSubscriptionResponse, error)
	UpdateSubscription(ctx context.Context, in *UpdateSubscriptionRequest, opts ...grpc.CallOption) (*UpdateSubscriptionResponse, error)
	DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionResponse, error)
	ListSubscriptions(ctx context.Context, in *ListSubscriptionsRequest, opts ...grpc.CallOption) (*ListSubscriptionsResponse, error)
	// --- Subscription attachments ---
	CreateSubscriptionAttachment(ctx context.Context, in *CreateSubscriptionAttachmentRequest, opts ...grpc.CallOption) (*CreateSubscriptionAttachmentResponse, error)
	DeleteSubscriptionAttachment(ctx context.Context, in *DeleteSubscriptionAttachmentRequest, opts ...grpc.CallOption) (*DeleteSubscriptionAttachmentResponse, error)
	ListSubscriptionAttachments(ctx context.Context, in *ListSubscriptionAttachmentsRequest, opts ...grpc.CallOption) (*ListSubscriptionAttachmentsResponse, error)
	// --- Test ---
	TestModel(ctx context.Context, in *TestModelRequest, opts ...grpc.CallOption) (*TestModelResponse, error)
	// --- Resolution ---
	ResolveModel(ctx context.Context, in *ResolveModelRequest, opts ...grpc.CallOption) (*ResolveModelResponse, error)
	ResolveSubscription(ctx context.Context, in *ResolveSubscriptionRequest, opts ...grpc.CallOption) (*ResolveSubscriptionResponse, error)
	// --- Internal ---
	// Secrets -> refuse deleting a secret a subscription references.
	CountSubscriptionsReferencingSecret(ctx context.Context, in *CountSubscriptionsReferencingSecretRequest, opts ...grpc.CallOption) (*CountSubscriptionsReferencingSecretResponse, error)
}

type lLMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMServiceClient(cc grpc.ClientConnInterface) LLMServiceClient {
	return &lLMServiceClient{cc}
}

func (c *lLMServiceClient) CreateLLMProvider(ctx context.Context, in *CreateLLMProviderRequest, opts ...grpc.CallOption) (*CreateLLMProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLLMProviderResponse)
	err := c.cc.Invoke(ctx, LLMService_CreateLLMProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) GetLLMProvider(ctx context.Context, in *GetLLMProviderRequest, opts ...grpc.CallOption) (*GetLLMProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLLMProviderResponse)
	err := c.cc.Invoke(ctx, LLMService_GetLLMProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) UpdateLLMProvider(ctx context.Context, in *UpdateLLMProviderRequest, opts ...grpc.CallOption) (*UpdateLLMProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLLMProviderResponse)
	err := c.cc.Invoke(ctx, LLMService_UpdateLLMProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) DeleteLLMProvider(ctx context.Context, in *DeleteLLMProviderRequest, opts ...grpc.CallOption) (*DeleteLLMProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLLMProviderResponse)
	err := c.cc.Invoke(ctx, LLMService_DeleteLLMProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) ListLLMProviders(ctx context.Context, in *ListLLMProvidersRequest, opts ...grpc.CallOption) (*ListLLMProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLLMProvidersResponse)
	err := c.cc.Invoke(ctx, LLMService_ListLLMProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateModelResponse)
	err := c.cc.Invoke(ctx, LLMService_CreateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelResponse)
	err := c.cc.Invoke(ctx, LLMService_GetModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*UpdateModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateModelResponse)
	err := c.cc.Invoke(ctx, LLMService_UpdateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteModelResponse)
	err := c.cc.Invoke(ctx, LLMService_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, LLMService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) CreateSubscription(ctx context.Context, in *CreateSubscriptionRequest, opts ...grpc.CallOption) (*CreateSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubscriptionResponse)
	err := c.cc.Invoke(ctx, LLMService_CreateSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) GetSubscription(ctx context.Context, in *GetSubscriptionRequest, opts ...grpc.CallOption) (*GetSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubscriptionResponse)
	err := c.cc.Invoke(ctx, LLMService_GetSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) UpdateSubscription(ctx context.Context, in *UpdateSubscriptionRequest, opts ...grpc.CallOption) (*UpdateSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSubscriptionResponse)
	err := c.cc.Invoke(ctx, LLMService_UpdateSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) DeleteSubscription(ctx context.Context, in *DeleteSubscriptionRequest, opts ...grpc.CallOption) (*DeleteSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSubscriptionResponse)
	err := c.cc.Invoke(ctx, LLMService_DeleteSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) ListSubscriptions(ctx context.Context, in *ListSubscriptionsRequest, opts ...grpc.CallOption) (*ListSubscriptionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubscriptionsResponse)
	err := c.cc.Invoke(ctx, LLMService_ListSubscriptions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) CreateSubscriptionAttachment(ctx context.Context, in *CreateSubscriptionAttachmentRequest, opts ...grpc.CallOption) (*CreateSubscriptionAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSubscriptionAttachmentResponse)
	err := c.cc.Invoke(ctx, LLMService_CreateSubscriptionAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) DeleteSubscriptionAttachment(ctx context.Context, in *DeleteSubscriptionAttachmentRequest, opts ...grpc.CallOption) (*DeleteSubscriptionAttachmentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSubscriptionAttachmentResponse)
	err := c.cc.Invoke(ctx, LLMService_DeleteSubscriptionAttachment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) ListSubscriptionAttachments(ctx context.Context, in *ListSubscriptionAttachmentsRequest, opts ...grpc.CallOption) (*ListSubscriptionAttachmentsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSubscriptionAttachmentsResponse)
	err := c.cc.Invoke(ctx, LLMService_ListSubscriptionAttachments_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) TestModel(ctx context.Context, in *TestModelRequest, opts ...grpc.CallOption) (*TestModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TestModelResponse)
	err := c.cc.Invoke(ctx, LLMService_TestModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) ResolveModel(ctx context.Context, in *ResolveModelRequest, opts ...grpc.CallOption) (*ResolveModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveModelResponse)
	err := c.cc.Invoke(ctx, LLMService_ResolveModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) ResolveSubscription(ctx context.Context, in *ResolveSubscriptionRequest, opts ...grpc.CallOption) (*ResolveSubscriptionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveSubscriptionResponse)
	err := c.cc.Invoke(ctx, LLMService_ResolveSubscription_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) CountSubscriptionsReferencingSecret(ctx context.Context, in *CountSubscriptionsReferencingSecretRequest, opts ...grpc.CallOption) (*CountSubscriptionsReferencingSecretResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountSubscriptionsReferencingSecretResponse)
	err := c.cc.Invoke(ctx, LLMService_CountSubscriptionsReferencingSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMServiceServer is the server API for LLMService service.
// All implementations should embed UnimplementedLLMServiceServer
// for forward compatibility.
//
// LLMService manages provider, model, and subscription resources and resolves
// them for the LLM Proxy.
type LLMServiceServer interface {
	// --- Providers ---
	CreateLLMProvider(context.Context, *CreateLLMProviderRequest) (*CreateLLMProviderResponse, error)
	GetLLMProvider(context.Context, *GetLLMProviderRequest) (*GetLLMProviderResponse, error)
	UpdateLLMProvider(context.Context, *UpdateLLMProviderRequest) (*UpdateLLMProviderResponse, error)
	DeleteLLMProvider(context.Context, *DeleteLLMProviderRequest) (*DeleteLLMProviderResponse, error)
	ListLLMProviders(context.Context, *ListLLMProvidersRequest) (*ListLLMProvidersResponse, error)
	// --- Models ---
	CreateModel(context.Context, *CreateModelRequest) (*CreateModelResponse, error)
	GetModel(context.Context, *GetModelRequest) (*GetModelResponse, error)
	UpdateModel(context.Context, *UpdateModelRequest) (*UpdateModelResponse, error)
	DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	// --- Subscriptions ---
	CreateSubscription(context.Context, *CreateSubscriptionRequest) (*CreateSubscriptionResponse, error)
	GetSubscription(context.Context, *GetSubscriptionRequest) (*GetSubscriptionResponse, error)
	UpdateSubscription(context.Context, *UpdateSubscriptionRequest) (*UpdateSubscriptionResponse, error)
	DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*DeleteSubscriptionResponse, error)
	ListSubscriptions(context.Context, *ListSubscriptionsRequest) (*ListSubscriptionsResponse, error)
	// --- Subscription attachments ---
	CreateSubscriptionAttachment(context.Context, *CreateSubscriptionAttachmentRequest) (*CreateSubscriptionAttachmentResponse, error)
	DeleteSubscriptionAttachment(context.Context, *DeleteSubscriptionAttachmentRequest) (*DeleteSubscriptionAttachmentResponse, error)
	ListSubscriptionAttachments(context.Context, *ListSubscriptionAttachmentsRequest) (*ListSubscriptionAttachmentsResponse, error)
	// --- Test ---
	TestModel(context.Context, *TestModelRequest) (*TestModelResponse, error)
	// --- Resolution ---
	ResolveModel(context.Context, *ResolveModelRequest) (*ResolveModelResponse, error)
	ResolveSubscription(context.Context, *ResolveSubscriptionRequest) (*ResolveSubscriptionResponse, error)
	// --- Internal ---
	// Secrets -> refuse deleting a secret a subscription references.
	CountSubscriptionsReferencingSecret(context.Context, *CountSubscriptionsReferencingSecretRequest) (*CountSubscriptionsReferencingSecretResponse, error)
}

// UnimplementedLLMServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMServiceServer struct{}

func (UnimplementedLLMServiceServer) CreateLLMProvider(context.Context, *CreateLLMProviderRequest) (*CreateLLMProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLLMProvider not implemented")
}
func (UnimplementedLLMServiceServer) GetLLMProvider(context.Context, *GetLLMProviderRequest) (*GetLLMProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLLMProvider not implemented")
}
func (UnimplementedLLMServiceServer) UpdateLLMProvider(context.Context, *UpdateLLMProviderRequest) (*UpdateLLMProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLLMProvider not implemented")
}
func (UnimplementedLLMServiceServer) DeleteLLMProvider(context.Context, *DeleteLLMProviderRequest) (*DeleteLLMProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLLMProvider not implemented")
}
func (UnimplementedLLMServiceServer) ListLLMProviders(context.Context, *ListLLMProvidersRequest) (*ListLLMProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLLMProviders not implemented")
}
func (UnimplementedLLMServiceServer) CreateModel(context.Context, *CreateModelRequest) (*CreateModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateModel not implemented")
}
func (UnimplementedLLMServiceServer) GetModel(context.Context, *GetModelRequest) (*GetModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModel not implemented")
}
func (UnimplementedLLMServiceServer) UpdateModel(context.Context, *UpdateModelRequest) (*UpdateModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateModel not implemented")
}
func (UnimplementedLLMServiceServer) DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedLLMServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedLLMServiceServer) CreateSubscription(context.Context, *CreateSubscriptionRequest) (*CreateSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSubscription not implemented")
}
func (UnimplementedLLMServiceServer) GetSubscription(context.Context, *GetSubscriptionRequest) (*GetSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubscription not implemented")
}
func (UnimplementedLLMServiceServer) UpdateSubscription(context.Context, *UpdateSubscriptionRequest) (*UpdateSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSubscription not implemented")
}
func (UnimplementedLLMServiceServer) DeleteSubscription(context.Context, *DeleteSubscriptionRequest) (*DeleteSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSubscription not implemented")
}
func (UnimplementedLLMServiceServer) ListSubscriptions(context.Context, *ListSubscriptionsRequest) (*ListSubscriptionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubscriptions not implemented")
}
func (UnimplementedLLMServiceServer) CreateSubscriptionAttachment(context.Context, *CreateSubscriptionAttachmentRequest) (*CreateSubscriptionAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSubscriptionAttachment not implemented")
}
func (UnimplementedLLMServiceServer) DeleteSubscriptionAttachment(context.Context, *DeleteSubscriptionAttachmentRequest) (*DeleteSubscriptionAttachmentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteSubscriptionAttachment not implemented")
}
func (UnimplementedLLMServiceServer) ListSubscriptionAttachments(context.Context, *ListSubscriptionAttachmentsRequest) (*ListSubscriptionAttachmentsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSubscriptionAttachments not implemented")
}
func (UnimplementedLLMServiceServer) TestModel(context.Context, *TestModelRequest) (*TestModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TestModel not implemented")
}
func (UnimplementedLLMServiceServer) ResolveModel(context.Context, *ResolveModelRequest) (*ResolveModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveModel not implemented")
}
func (UnimplementedLLMServiceServer) ResolveSubscription(context.Context, *ResolveSubscriptionRequest) (*ResolveSubscriptionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveSubscription not implemented")
}
func (UnimplementedLLMServiceServer) CountSubscriptionsReferencingSecret(context.Context, *CountSubscriptionsReferencingSecretRequest) (*CountSubscriptionsReferencingSecretResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CountSubscriptionsReferencingSecret not implemented")
}
func (UnimplementedLLMServiceServer) testEmbeddedByValue() {}

// UnsafeLLMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMServiceServer will
// result in compilation errors.
type UnsafeLLMServiceServer interface {
	mustEmbedUnimplementedLLMServiceServer()
}

func RegisterLLMServiceServer(s grpc.ServiceRegistrar, srv LLMServiceServer) {
	// If the following call panics, it indicates UnimplementedLLMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMService_ServiceDesc, srv)
}

func _LLMService_CreateLLMProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLLMProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).CreateLLMProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_CreateLLMProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).CreateLLMProvider(ctx, req.(*CreateLLMProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_GetLLMProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLLMProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).GetLLMProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_GetLLMProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).GetLLMProvider(ctx, req.(*GetLLMProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_UpdateLLMProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLLMProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).UpdateLLMProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_UpdateLLMProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).UpdateLLMProvider(ctx, req.(*UpdateLLMProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_DeleteLLMProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLLMProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).DeleteLLMProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_DeleteLLMProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).DeleteLLMProvider(ctx, req.(*DeleteLLMProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_ListLLMProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLLMProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).ListLLMProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_ListLLMProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).ListLLMProviders(ctx, req.(*ListLLMProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_CreateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).CreateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_CreateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).CreateModel(ctx, req.(*CreateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_GetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).GetModel(ctx, req.(*GetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_UpdateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).UpdateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_UpdateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).UpdateModel(ctx, req.(*UpdateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).DeleteModel(ctx, req.(*DeleteModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_CreateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).CreateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_CreateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).CreateSubscription(ctx, req.(*CreateSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_GetSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).GetSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_GetSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).GetSubscription(ctx, req.(*GetSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_UpdateSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).UpdateSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_UpdateSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).UpdateSubscription(ctx, req.(*UpdateSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_DeleteSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).DeleteSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_DeleteSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).DeleteSubscription(ctx, req.(*DeleteSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_ListSubscriptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubscriptionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).ListSubscriptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_ListSubscriptions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).ListSubscriptions(ctx, req.(*ListSubscriptionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_CreateSubscriptionAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSubscriptionAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).CreateSubscriptionAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_CreateSubscriptionAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).CreateSubscriptionAttachment(ctx, req.(*CreateSubscriptionAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_DeleteSubscriptionAttachment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSubscriptionAttachmentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).DeleteSubscriptionAttachment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_DeleteSubscriptionAttachment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).DeleteSubscriptionAttachment(ctx, req.(*DeleteSubscriptionAttachmentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_ListSubscriptionAttachments_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSubscriptionAttachmentsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).ListSubscriptionAttachments(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_ListSubscriptionAttachments_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).ListSubscriptionAttachments(ctx, req.(*ListSubscriptionAttachmentsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_TestModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TestModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).TestModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_TestModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).TestModel(ctx, req.(*TestModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_ResolveModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).ResolveModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_ResolveModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).ResolveModel(ctx, req.(*ResolveModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_ResolveSubscription_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveSubscriptionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).ResolveSubscription(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_ResolveSubscription_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).ResolveSubscription(ctx, req.(*ResolveSubscriptionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_CountSubscriptionsReferencingSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountSubscriptionsReferencingSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).CountSubscriptionsReferencingSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_CountSubscriptionsReferencingSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).CountSubscriptionsReferencingSecret(ctx, req.(*CountSubscriptionsReferencingSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMService_ServiceDesc is the grpc.ServiceDesc for LLMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agynio.api.llm.v1.LLMService",
	HandlerType: (*LLMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLLMProvider",
			Handler:    _LLMService_CreateLLMProvider_Handler,
		},
		{
			MethodName: "GetLLMProvider",
			Handler:    _LLMService_GetLLMProvider_Handler,
		},
		{
			MethodName: "UpdateLLMProvider",
			Handler:    _LLMService_UpdateLLMProvider_Handler,
		},
		{
			MethodName: "DeleteLLMProvider",
			Handler:    _LLMService_DeleteLLMProvider_Handler,
		},
		{
			MethodName: "ListLLMProviders",
			Handler:    _LLMService_ListLLMProviders_Handler,
		},
		{
			MethodName: "CreateModel",
			Handler:    _LLMService_CreateModel_Handler,
		},
		{
			MethodName: "GetModel",
			Handler:    _LLMService_GetModel_Handler,
		},
		{
			MethodName: "UpdateModel",
			Handler:    _LLMService_UpdateModel_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _LLMService_DeleteModel_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _LLMService_ListModels_Handler,
		},
		{
			MethodName: "CreateSubscription",
			Handler:    _LLMService_CreateSubscription_Handler,
		},
		{
			MethodName: "GetSubscription",
			Handler:    _LLMService_GetSubscription_Handler,
		},
		{
			MethodName: "UpdateSubscription",
			Handler:    _LLMService_UpdateSubscription_Handler,
		},
		{
			MethodName: "DeleteSubscription",
			Handler:    _LLMService_DeleteSubscription_Handler,
		},
		{
			MethodName: "ListSubscriptions",
			Handler:    _LLMService_ListSubscriptions_Handler,
		},
		{
			MethodName: "CreateSubscriptionAttachment",
			Handler:    _LLMService_CreateSubscriptionAttachment_Handler,
		},
		{
			MethodName: "DeleteSubscriptionAttachment",
			Handler:    _LLMService_DeleteSubscriptionAttachment_Handler,
		},
		{
			MethodName: "ListSubscriptionAttachments",
			Handler:    _LLMService_ListSubscriptionAttachments_Handler,
		},
		{
			MethodName: "TestModel",
			Handler:    _LLMService_TestModel_Handler,
		},
		{
			MethodName: "ResolveModel",
			Handler:    _LLMService_ResolveModel_Handler,
		},
		{
			MethodName: "ResolveSubscription",
			Handler:    _LLMService_ResolveSubscription_Handler,
		},
		{
			MethodName: "CountSubscriptionsReferencingSecret",
			Handler:    _LLMService_CountSubscriptionsReferencingSecret_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agynio/api/llm/v1/llm.proto",
}
