// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: agynio/api/llm/v1/llm.proto

package llmv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LLMService_CreateLLMProvider_FullMethodName = "/agynio.api.llm.v1.LLMService/CreateLLMProvider"
	LLMService_GetLLMProvider_FullMethodName    = "/agynio.api.llm.v1.LLMService/GetLLMProvider"
	LLMService_UpdateLLMProvider_FullMethodName = "/agynio.api.llm.v1.LLMService/UpdateLLMProvider"
	LLMService_DeleteLLMProvider_FullMethodName = "/agynio.api.llm.v1.LLMService/DeleteLLMProvider"
	LLMService_ListLLMProviders_FullMethodName  = "/agynio.api.llm.v1.LLMService/ListLLMProviders"
	LLMService_CreateModel_FullMethodName       = "/agynio.api.llm.v1.LLMService/CreateModel"
	LLMService_GetModel_FullMethodName          = "/agynio.api.llm.v1.LLMService/GetModel"
	LLMService_UpdateModel_FullMethodName       = "/agynio.api.llm.v1.LLMService/UpdateModel"
	LLMService_DeleteModel_FullMethodName       = "/agynio.api.llm.v1.LLMService/DeleteModel"
	LLMService_ListModels_FullMethodName        = "/agynio.api.llm.v1.LLMService/ListModels"
	LLMService_ResolveModel_FullMethodName      = "/agynio.api.llm.v1.LLMService/ResolveModel"
)

// LLMServiceClient is the client API for LLMService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LLMService manages provider and model resources and resolves models.
type LLMServiceClient interface {
	// --- Providers ---
	CreateLLMProvider(ctx context.Context, in *CreateLLMProviderRequest, opts ...grpc.CallOption) (*CreateLLMProviderResponse, error)
	GetLLMProvider(ctx context.Context, in *GetLLMProviderRequest, opts ...grpc.CallOption) (*GetLLMProviderResponse, error)
	UpdateLLMProvider(ctx context.Context, in *UpdateLLMProviderRequest, opts ...grpc.CallOption) (*UpdateLLMProviderResponse, error)
	DeleteLLMProvider(ctx context.Context, in *DeleteLLMProviderRequest, opts ...grpc.CallOption) (*DeleteLLMProviderResponse, error)
	ListLLMProviders(ctx context.Context, in *ListLLMProvidersRequest, opts ...grpc.CallOption) (*ListLLMProvidersResponse, error)
	// --- Models ---
	CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelResponse, error)
	GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelResponse, error)
	UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*UpdateModelResponse, error)
	DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error)
	ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error)
	// --- Resolution ---
	ResolveModel(ctx context.Context, in *ResolveModelRequest, opts ...grpc.CallOption) (*ResolveModelResponse, error)
}

type lLMServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLLMServiceClient(cc grpc.ClientConnInterface) LLMServiceClient {
	return &lLMServiceClient{cc}
}

func (c *lLMServiceClient) CreateLLMProvider(ctx context.Context, in *CreateLLMProviderRequest, opts ...grpc.CallOption) (*CreateLLMProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateLLMProviderResponse)
	err := c.cc.Invoke(ctx, LLMService_CreateLLMProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) GetLLMProvider(ctx context.Context, in *GetLLMProviderRequest, opts ...grpc.CallOption) (*GetLLMProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetLLMProviderResponse)
	err := c.cc.Invoke(ctx, LLMService_GetLLMProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) UpdateLLMProvider(ctx context.Context, in *UpdateLLMProviderRequest, opts ...grpc.CallOption) (*UpdateLLMProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLLMProviderResponse)
	err := c.cc.Invoke(ctx, LLMService_UpdateLLMProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) DeleteLLMProvider(ctx context.Context, in *DeleteLLMProviderRequest, opts ...grpc.CallOption) (*DeleteLLMProviderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteLLMProviderResponse)
	err := c.cc.Invoke(ctx, LLMService_DeleteLLMProvider_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) ListLLMProviders(ctx context.Context, in *ListLLMProvidersRequest, opts ...grpc.CallOption) (*ListLLMProvidersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListLLMProvidersResponse)
	err := c.cc.Invoke(ctx, LLMService_ListLLMProviders_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) CreateModel(ctx context.Context, in *CreateModelRequest, opts ...grpc.CallOption) (*CreateModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateModelResponse)
	err := c.cc.Invoke(ctx, LLMService_CreateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) GetModel(ctx context.Context, in *GetModelRequest, opts ...grpc.CallOption) (*GetModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetModelResponse)
	err := c.cc.Invoke(ctx, LLMService_GetModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) UpdateModel(ctx context.Context, in *UpdateModelRequest, opts ...grpc.CallOption) (*UpdateModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateModelResponse)
	err := c.cc.Invoke(ctx, LLMService_UpdateModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) DeleteModel(ctx context.Context, in *DeleteModelRequest, opts ...grpc.CallOption) (*DeleteModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteModelResponse)
	err := c.cc.Invoke(ctx, LLMService_DeleteModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) ListModels(ctx context.Context, in *ListModelsRequest, opts ...grpc.CallOption) (*ListModelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListModelsResponse)
	err := c.cc.Invoke(ctx, LLMService_ListModels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lLMServiceClient) ResolveModel(ctx context.Context, in *ResolveModelRequest, opts ...grpc.CallOption) (*ResolveModelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveModelResponse)
	err := c.cc.Invoke(ctx, LLMService_ResolveModel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LLMServiceServer is the server API for LLMService service.
// All implementations should embed UnimplementedLLMServiceServer
// for forward compatibility.
//
// LLMService manages provider and model resources and resolves models.
type LLMServiceServer interface {
	// --- Providers ---
	CreateLLMProvider(context.Context, *CreateLLMProviderRequest) (*CreateLLMProviderResponse, error)
	GetLLMProvider(context.Context, *GetLLMProviderRequest) (*GetLLMProviderResponse, error)
	UpdateLLMProvider(context.Context, *UpdateLLMProviderRequest) (*UpdateLLMProviderResponse, error)
	DeleteLLMProvider(context.Context, *DeleteLLMProviderRequest) (*DeleteLLMProviderResponse, error)
	ListLLMProviders(context.Context, *ListLLMProvidersRequest) (*ListLLMProvidersResponse, error)
	// --- Models ---
	CreateModel(context.Context, *CreateModelRequest) (*CreateModelResponse, error)
	GetModel(context.Context, *GetModelRequest) (*GetModelResponse, error)
	UpdateModel(context.Context, *UpdateModelRequest) (*UpdateModelResponse, error)
	DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error)
	ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error)
	// --- Resolution ---
	ResolveModel(context.Context, *ResolveModelRequest) (*ResolveModelResponse, error)
}

// UnimplementedLLMServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLLMServiceServer struct{}

func (UnimplementedLLMServiceServer) CreateLLMProvider(context.Context, *CreateLLMProviderRequest) (*CreateLLMProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateLLMProvider not implemented")
}
func (UnimplementedLLMServiceServer) GetLLMProvider(context.Context, *GetLLMProviderRequest) (*GetLLMProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLLMProvider not implemented")
}
func (UnimplementedLLMServiceServer) UpdateLLMProvider(context.Context, *UpdateLLMProviderRequest) (*UpdateLLMProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLLMProvider not implemented")
}
func (UnimplementedLLMServiceServer) DeleteLLMProvider(context.Context, *DeleteLLMProviderRequest) (*DeleteLLMProviderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteLLMProvider not implemented")
}
func (UnimplementedLLMServiceServer) ListLLMProviders(context.Context, *ListLLMProvidersRequest) (*ListLLMProvidersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListLLMProviders not implemented")
}
func (UnimplementedLLMServiceServer) CreateModel(context.Context, *CreateModelRequest) (*CreateModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateModel not implemented")
}
func (UnimplementedLLMServiceServer) GetModel(context.Context, *GetModelRequest) (*GetModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetModel not implemented")
}
func (UnimplementedLLMServiceServer) UpdateModel(context.Context, *UpdateModelRequest) (*UpdateModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateModel not implemented")
}
func (UnimplementedLLMServiceServer) DeleteModel(context.Context, *DeleteModelRequest) (*DeleteModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteModel not implemented")
}
func (UnimplementedLLMServiceServer) ListModels(context.Context, *ListModelsRequest) (*ListModelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListModels not implemented")
}
func (UnimplementedLLMServiceServer) ResolveModel(context.Context, *ResolveModelRequest) (*ResolveModelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveModel not implemented")
}
func (UnimplementedLLMServiceServer) testEmbeddedByValue() {}

// UnsafeLLMServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LLMServiceServer will
// result in compilation errors.
type UnsafeLLMServiceServer interface {
	mustEmbedUnimplementedLLMServiceServer()
}

func RegisterLLMServiceServer(s grpc.ServiceRegistrar, srv LLMServiceServer) {
	// If the following call panics, it indicates UnimplementedLLMServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LLMService_ServiceDesc, srv)
}

func _LLMService_CreateLLMProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateLLMProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).CreateLLMProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_CreateLLMProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).CreateLLMProvider(ctx, req.(*CreateLLMProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_GetLLMProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLLMProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).GetLLMProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_GetLLMProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).GetLLMProvider(ctx, req.(*GetLLMProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_UpdateLLMProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLLMProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).UpdateLLMProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_UpdateLLMProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).UpdateLLMProvider(ctx, req.(*UpdateLLMProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_DeleteLLMProvider_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteLLMProviderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).DeleteLLMProvider(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_DeleteLLMProvider_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).DeleteLLMProvider(ctx, req.(*DeleteLLMProviderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_ListLLMProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListLLMProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).ListLLMProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_ListLLMProviders_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).ListLLMProviders(ctx, req.(*ListLLMProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_CreateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).CreateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_CreateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).CreateModel(ctx, req.(*CreateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_GetModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).GetModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_GetModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).GetModel(ctx, req.(*GetModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_UpdateModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).UpdateModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_UpdateModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).UpdateModel(ctx, req.(*UpdateModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_DeleteModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).DeleteModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_DeleteModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).DeleteModel(ctx, req.(*DeleteModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_ListModels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListModelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).ListModels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_ListModels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).ListModels(ctx, req.(*ListModelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LLMService_ResolveModel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveModelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LLMServiceServer).ResolveModel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LLMService_ResolveModel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LLMServiceServer).ResolveModel(ctx, req.(*ResolveModelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LLMService_ServiceDesc is the grpc.ServiceDesc for LLMService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LLMService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "agynio.api.llm.v1.LLMService",
	HandlerType: (*LLMServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateLLMProvider",
			Handler:    _LLMService_CreateLLMProvider_Handler,
		},
		{
			MethodName: "GetLLMProvider",
			Handler:    _LLMService_GetLLMProvider_Handler,
		},
		{
			MethodName: "UpdateLLMProvider",
			Handler:    _LLMService_UpdateLLMProvider_Handler,
		},
		{
			MethodName: "DeleteLLMProvider",
			Handler:    _LLMService_DeleteLLMProvider_Handler,
		},
		{
			MethodName: "ListLLMProviders",
			Handler:    _LLMService_ListLLMProviders_Handler,
		},
		{
			MethodName: "CreateModel",
			Handler:    _LLMService_CreateModel_Handler,
		},
		{
			MethodName: "GetModel",
			Handler:    _LLMService_GetModel_Handler,
		},
		{
			MethodName: "UpdateModel",
			Handler:    _LLMService_UpdateModel_Handler,
		},
		{
			MethodName: "DeleteModel",
			Handler:    _LLMService_DeleteModel_Handler,
		},
		{
			MethodName: "ListModels",
			Handler:    _LLMService_ListModels_Handler,
		},
		{
			MethodName: "ResolveModel",
			Handler:    _LLMService_ResolveModel_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agynio/api/llm/v1/llm.proto",
}
